CREATE TABLE "PersonalDetails" (
  "personal_details_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "personal_number" char(12) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "phone" varchar(50)
);

CREATE TABLE "Student" (
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personal_details_id" int NOT NULL,
  "class_id" int NOT NULL
);

CREATE TABLE "ProgramManager" (
  "program_manager_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personal_details_id" int NOT NULL
);

CREATE TABLE "Facility" (
  "facility_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL
);

CREATE TABLE "Program" (
  "program_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_name" varchar(255) NOT NULL,
  "description" text
);

CREATE TABLE "Class" (
  "class_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_name" varchar(100) NOT NULL,
  "program_id" int NOT NULL,
  "program_manager_id" int NOT NULL,
  "facility_id" int NOT NULL
);

CREATE TABLE "Course" (
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_name" varchar(255) NOT NULL,
  "course_code" varchar(50) UNIQUE NOT NULL,
  "credits" int NOT NULL,
  "description" text
);

CREATE TABLE "Program_Course" (
  "program_id" int,
  "course_id" int,
  PRIMARY KEY ("program_id", "course_id")
);

CREATE TABLE "ConsultingCompany" (
  "consulting_company_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" varchar(255) NOT NULL,
  "organization_number" varchar(50) UNIQUE NOT NULL,
  "address" varchar(255),
  "has_f_tax" boolean NOT NULL,
  "hourly_rate" numeric(10,2)
);

CREATE TABLE "Instructor" (
  "instructor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personal_details_id" int NOT NULL,
  "consulting_company_id" int,
  "employment_type" varchar(20) NOT NULL
);

CREATE TABLE "Course_Instructor" (
  "instructor_id" int,
  "course_id" int,
  PRIMARY KEY ("instructor_id", "course_id")
);

ALTER TABLE "Student" ADD FOREIGN KEY ("personal_details_id") REFERENCES "PersonalDetails" ("personal_details_id");

ALTER TABLE "Student" ADD FOREIGN KEY ("class_id") REFERENCES "Class" ("class_id");

ALTER TABLE "ProgramManager" ADD FOREIGN KEY ("personal_details_id") REFERENCES "PersonalDetails" ("personal_details_id");

ALTER TABLE "Class" ADD FOREIGN KEY ("program_id") REFERENCES "Program" ("program_id");

ALTER TABLE "Class" ADD FOREIGN KEY ("program_manager_id") REFERENCES "ProgramManager" ("program_manager_id");

ALTER TABLE "Class" ADD FOREIGN KEY ("facility_id") REFERENCES "Facility" ("facility_id");

ALTER TABLE "Program_Course" ADD FOREIGN KEY ("program_id") REFERENCES "Program" ("program_id");

ALTER TABLE "Program_Course" ADD FOREIGN KEY ("course_id") REFERENCES "Course" ("course_id");

ALTER TABLE "Instructor" ADD FOREIGN KEY ("personal_details_id") REFERENCES "PersonalDetails" ("personal_details_id");

ALTER TABLE "Instructor" ADD FOREIGN KEY ("consulting_company_id") REFERENCES "ConsultingCompany" ("consulting_company_id");

ALTER TABLE "Course_Instructor" ADD FOREIGN KEY ("instructor_id") REFERENCES "Instructor" ("instructor_id");

ALTER TABLE "Course_Instructor" ADD FOREIGN KEY ("course_id") REFERENCES "Course" ("course_id");
