CREATE TABLE "personuppgifter" (
  "personuppgifter_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fornamn" varchar(100) NOT NULL,
  "efternamn" varchar(100) NOT NULL,
  "personnummer" char(12) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "telefon" varchar(50)
);

CREATE TABLE "student" (
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personuppgifter_id" int NOT NULL,
  "klass_id" int NOT NULL
);

CREATE TABLE "utbildningsledare" (
  "utbildningsledare_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personuppgifter_id" int NOT NULL
);

CREATE TABLE "anlaggning" (
  "anlaggning_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adress" varchar(255) NOT NULL,
  "ort" varchar(100) NOT NULL
);

CREATE TABLE "program" (
  "program_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_namn" varchar(255) NOT NULL,
  "beskrivning" text
);

CREATE TABLE "klass" (
  "klass_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "klass_namn" varchar(100) NOT NULL,
  "program_id" int NOT NULL,
  "utbildningsledare_id" int NOT NULL,
  "anlaggning_id" int NOT NULL
);

CREATE TABLE "kurs" (
  "kurs_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kurs_namn" varchar(255) NOT NULL,
  "kurskod" varchar(50) UNIQUE NOT NULL,
  "poang" int NOT NULL,
  "beskrivning" text
);

CREATE TABLE "program_kurs" (
  "program_id" int,
  "kurs_id" int,
  PRIMARY KEY ("program_id", "kurs_id")
);

CREATE TABLE "konsult_foretag" (
  "konsult_foretag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "foretagsnamn" varchar(255) NOT NULL,
  "organisationsnummer" varchar(50) UNIQUE NOT NULL,
  "adress" varchar(255),
  "har_f_skatt" boolean NOT NULL,
  "timarvode" numeric(10,2)
);

CREATE TABLE "utbildare" (
  "utbildare_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "konsult_foretag_id" int,
  "personuppgifter_id" int NOT NULL
);

CREATE TABLE "kurs_utbildare" (
  "utbildare_id" int,
  "kurs_id" int,
  PRIMARY KEY ("utbildare_id", "kurs_id")
);

ALTER TABLE "student" ADD FOREIGN KEY ("personuppgifter_id") REFERENCES "personuppgifter" ("personuppgifter_id");

ALTER TABLE "student" ADD FOREIGN KEY ("klass_id") REFERENCES "klass" ("klass_id");

ALTER TABLE "utbildningsledare" ADD FOREIGN KEY ("personuppgifter_id") REFERENCES "personuppgifter" ("personuppgifter_id");

ALTER TABLE "klass" ADD FOREIGN KEY ("program_id") REFERENCES "program" ("program_id");

ALTER TABLE "klass" ADD FOREIGN KEY ("utbildningsledare_id") REFERENCES "utbildningsledare" ("utbildningsledare_id");

ALTER TABLE "klass" ADD FOREIGN KEY ("anlaggning_id") REFERENCES "anlaggning" ("anlaggning_id");

ALTER TABLE "program_kurs" ADD FOREIGN KEY ("program_id") REFERENCES "program" ("program_id");

ALTER TABLE "program_kurs" ADD FOREIGN KEY ("kurs_id") REFERENCES "kurs" ("kurs_id");

ALTER TABLE "utbildare" ADD FOREIGN KEY ("konsult_foretag_id") REFERENCES "konsult_foretag" ("konsult_foretag_id");

ALTER TABLE "utbildare" ADD FOREIGN KEY ("personuppgifter_id") REFERENCES "personuppgifter" ("personuppgifter_id");

ALTER TABLE "kurs_utbildare" ADD FOREIGN KEY ("utbildare_id") REFERENCES "utbildare" ("utbildare_id");

ALTER TABLE "kurs_utbildare" ADD FOREIGN KEY ("kurs_id") REFERENCES "kurs" ("kurs_id");
